### ISSUE TITLE
Peer to peer Review

### ISSUE THREAD

**Issue by Yerimah** [ismailakinkunmi/Leaderboard#5]
@ismailakinkunmi 

You have done a great job on this project. Everything looks good and your codebase is clean.

However, it will be nice if you upgrade the image of the project on your README.md file. 

Secondly, the link to clone your repository is broken. replace the colon after `github.com` with a `/` and it will be fixed

Cheers!

Happy Coding!.

**Comment by ismailakinkunmi** [comment]
Thanks, @Yerimah, I have fixed it.
